from app.core.models.resp.core_response import CoreStatus as s

to_http = {
    s.EMAIL_ALREADY_IN_USE: 400,
    s.SUCCESSFUL_GET: 200,
    s.USER_CREATED: 201,
    s.INVALID_API_KEY: 403,
    s.INVALID_REQUEST: 400,
    s.SUCCESSFUL_POST: 201,
    s.UNSUCCESSFUL_GET: 404,
    s.UNSUCCESSFUL_POST: 404,
    s.INVALID_ADMIN_KEY: 403,
    s.WALLET_DOESNT_BELONG_TO_USER: 400,
    s.INSUFFICIENT_FUNDS: 400,
    s.WALLET_LIMIT_REACHED: 400,
    s.WALLET_ADDRESS_NOT_FOUND: 404,
    s.WALLET_ADDRESS_TAKEN: 400,
}
